# -*- coding: utf-8 -*-
"""PseudoPython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAIxmQrxTkq_atQ3Mfccz0DvqiuEdmfr
"""

1. Função: processar_vendas

def processar_vendas():

  total_compra = 0.0

  itens_comprados = 0



  quantidades_tipos = int(input("Quantos produtos diferentes foram comprados?"))



  for i in range(quantidades_tipos):

    nome = input("Digite o nome do produto: ")

    preco = float(input("Preço unitário: "))

    qtd = int(input("Quantos itens comprados?"))



    if preco <= 0 or qtd <= 0:

      return "Erro: Valores inválidos para ", nome

    else:

      subtotal = preco *qtd

      total_compra += subtotal

      itens_comprados += 1



  if total_compra > 500:

    total_final = total_compra *0.90 # 10 % de desconto

    print("Desconto de 10% aplicado!")

  elif total_compra > 200:

    total_final = total_compra * 0.95 # 5 % de desconto

  else:

    total_final = total_compra



  print(f"Foram comprados: {itens_comprados} produtos\nTotal a pagar: R${total_final}")



processar_vendas()





2. Função: analisar_clima





def analisar_clima():

  soma_temperaturas = 0.0

  dias_quentes = 0

  alerta_extremo = False



  for dia in range(7):

    temp = float(input(f"Digite a temperatura do {dia +1}° dia: "))

    soma_temperaturas += temp



    if temp > 35.0:

      dias_quentes = dias_quentes + 1



    if temp < 45.0 or temp < -5.0:

      alerta_extremo = True





  media = soma_temperaturas / 7

  print("Media semanal: ",media)

  print("Dias acima de 35°C: ", dias_quentes)



  if alerta_extremo:

    print("CUIDADO: Condições climáticas perigosas detectadas!")



  else:

    print("Clima dentro da normalidade operacional.")



analisar_clima()





3. Função: sistema_notas_turma





def sistema_notas_turmas():



  total_alunos = int(input("quantos alunos existem na turma? "))

  for j in range(total_alunos):

    aluno_nome = input("Digite o nome do aluno: ")

    n1 = float(input("Digite a primeira nota do aluno: "))

    n2 = float(input("Digite a segunda nota do aluno: "))

    media_aluno = (n1 + n2) / 2



  if media_aluno >= 7:

    print(f"{aluno_nome} aprovado com a media: {media_aluno}")



  elif media_aluno >= 5.0:

    print(f"{aluno_nome} recuperacao com a media: {media_aluno}")



  else:

    print(f"{aluno_nome} : Repprovado")



sistema_notas_turmas()





4. Função: simulador_poupanca



def simulador_poupanca():

  saldo = float(input('Valor inicial do investimento: '))

  taxa = float(input('Taxa de juros mensal: '))

  meses = int(input('Número de meses da simulação: '))





  for i in range(meses):

    aporte = float(input(f'Quanto deseja depositar no {i + 1}° mês? '))





    saldo += aporte

    juros = saldo * (taxa/100)

    saldo += juros





    print(f'Mês {i + 1}: Saldo atualizado = R${saldo:.2f}')





    if saldo > 10000:

      print(f'Parabéns! Você atingiu a meta de 10k no mês {i}.')



  print(f'Resultado final após {meses} meses: R${saldo:.2f}')





simulador_poupanca()