# -*- coding: utf-8 -*-
"""Desenhando Emojis com Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAIxmQrxTkq_atQ3Mfccz0DvqiuEdmfr
"""

# Estrutura base para o exercício
emoji_data = {
  "nome": "Smile",
  "grade": [
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 0
    [(255,255,0), (0,0,0),   (255,255,0), (0,0,0),   (255,255,0)], # Linha 1 (Olhos)
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 2
    [(255,255,0), (0,0,0),   (0,0,0),   (0,0,0),   (255,255,0)], # Linha 3 (Boca)
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)] # Linha 4
  ]
}

# TODO: Implemente os 3 níveis de FOR aqui
nova_grade = []

for key, valor in emoji_data.items():
 if key == "grade":
  for linha in valor: # Verificar as linhas
   nova_linha = []
   for pixel in linha: # Verificar cada pixel
    if pixel == (255,255,0):
     # Tupla pra mudar a cor do pixel para 50% reduzido
     pixel_sombra = (pixel[0] // 2, pixel[1] // 2, pixel[2] // 2)
     nova_linha.append(pixel_sombra)
    else:
     nova_linha.append(pixel)
   nova_grade.append(nova_linha)



emoji_data["grade"] = nova_grade

print(f"Emoji: {emoji_data['nome']}")
for linha in emoji_data["grade"]:
  print(linha)