# -*- coding: utf-8 -*-
"""Desenhando Emojis com Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAIxmQrxTkq_atQ3Mfccz0DvqiuEdmfr
"""

livro_de_receitas = {
    "Bolo de Chocolate": {
        "ingredientes": [
            ("farinha", 2, "xícaras"),
            ("açúcar", 1.5, "xícaras"),
            ("chocolate em pó", 0.5, "xícaras"),
            ("ovos", 3, "unidades"),
            ("leite", 1, "xícara")
        ],
        "passos": [
            ["Preparação da Massa", "Misture os ingredientes secos.", "Adicione os ovos e o leite.", "Bata até ficar homogêneo."],
            ["Cozimento", "Leve ao forno por 30 minutos."]
        ],
        "tempo_preparo_min": 45
    },
    "Omelete Simples": {
        "ingredientes": [
            ("ovos", 2, "unidades"),
            ("leite", 2, "colheres de sopa"),
            ("sal", 1, "pitada"),
            ("pimenta", 1, "pitada")
        ],
        "passos": [
            ["Preparo", "Bata os ovos com leite, sal e pimenta."],
            ["Cozimento", "Despeje em frigideira quente.", "Cozinhe até dourar."]
        ],
        "tempo_preparo_min": 10
    }
}


print("--- Meu Livro de Receitas ---")


# Usando método de dicionário: .keys()
print(f"\nReceitas disponíveis: {livro_de_receitas.keys()}")


# Nível 1: Iterar sobre as receitas no livro (dicionário)
for nome_receita, detalhes_receita in livro_de_receitas.items():
    print(f"\n>>> Receita: {nome_receita} <<<")
    print(f"Tempo de preparo: {detalhes_receita['tempo_preparo_min']} minutos")


    print("Ingredientes:")
    # Nível 2: Iterar sobre a lista de ingredientes (lista de tuplas)
    for ingrediente_tupla in detalhes_receita['ingredientes']:
        ingrediente_info_formatada = []
        # Nível 3: Iterar sobre os elementos da tupla do ingrediente
        for info in ingrediente_tupla:
            ingrediente_info_formatada.append(str(info))
        print(f"  - {' '.join(ingrediente_info_formatada)}")


    print("Passos:")
    # Nível 2: Iterar sobre os grupos de passos
    for indice_grupo, grupo_passos in enumerate(detalhes_receita['passos']):
        print(f"  {indice_grupo + 1}. {grupo_passos[0]}:") # Imprime o título do grupo
        # Nível 3: Iterar sobre os passos individuais dentro do grupo
        for passo_individual_idx, passo_individual in enumerate(grupo_passos[1:]): # Ignora o título, itera os passos
            print(f"    - {passo_individual_idx + 1}. {passo_individual}")


    # Demonstrar um método de lista: .append() e .pop() (simples, no último grupo)
    if detalhes_receita['passos']:
        last_group = detalhes_receita['passos'][-1]
        last_group.append("Sirva quente.")
        print(f"  (Adicionado 'Sirva quente.' ao último grupo de passos.)")
        last_group.pop()
        print(f"  (Removido último passo com .pop().)")


# Demonstrar método de lista: .insert()
# Adicionar um ingrediente na 2ª posição da receita 'Bolo de Chocolate'
livro_de_receitas['Bolo de Chocolate']['ingredientes'].insert(1, ("manteiga", 0.5, "barra"))
print(f"\nIngredientes do 'Bolo de Chocolate' após .insert():")
for nome, quant, uni in livro_de_receitas['Bolo de Chocolate']['ingredientes']:
    print(f"  - {quant} {uni} de {nome}")