# -*- coding: utf-8 -*-
"""Desenhando Emojis com Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAIxmQrxTkq_atQ3Mfccz0DvqiuEdmfr
"""

biblioteca_musical = {
  "Toques": [
    {"Alegre": ([440, 480], [520, 560])},
    {"Triste": ([200, 150], [100, 50])}
  ]
}
# TODO: Use 3 níveis de loops para acessar cada nota e inverter a matriz.

nova_lista_sons = []

for item_dicionario in biblioteca_musical["Toques"]: # Dicionario dos sentimentos
  for chave, grupo_notas in item_dicionario.items(): # Chave (sentimento) e valor das notas

    # Inverter as notas
    lista_notas_invertida = []
    for tupla_interna in reversed(grupo_notas):
      lista_notas_invertida.append(tupla_interna)
    grupo_notas_invertido = tuple(lista_notas_invertida)

    # Adiciona o sentimento a lista
    if chave == "Alegre":
      nova_lista_sons.append({"Triste": grupo_notas_invertido})
    elif chave == "Triste":
      nova_lista_sons.append({"Alegre": grupo_notas_invertido})

biblioteca_musical["Toques"] = nova_lista_sons

print("\nBiblioteca Musical:")
for item in biblioteca_musical['Toques']:
  for sentimento, valores in item.items():
    print(f"{sentimento}: {valores}")