# -*- coding: utf-8 -*-
"""sistema_auditoria

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgJKL2AGgFvmGyNeTpyA9Pw_bWS798Au

# Sistema de Auditoria de Recursos Corporativos

> Williams Vargas Neves Paoli dos Santos
"""

# Importar Biblioteca time para tempo e wraps pra não perder o valor original
import time
from functools import wraps

# Decorator da auditoria
def auditor(func):
  @wraps(func) # ← Chamando decorator na função
  def wrapper(*args, **kwargs):
    print("\n--- Ínicio da Auditoria ---")
    print(f"Função chamada: {func.__name__}")
    print(f"Args (posicionais): {args}")
    print(f"Kwargs (nomeados): {kwargs}")

    inicio = time.time()
    resultado = func(*args, **kwargs)
    fim = time.time()

    print(f"Tempo de execução: {fim - inicio:.6f} segundos")
    print("--- Fim da auditoria ---")
    return resultado
  return wrapper

# Estrutura de dados da Empresa em formato JSON

empresa_data = {
    "Matriz": {
        "TI": {
            "Infraestrutura": {
                "Servidores": 75000,
                "Seguranca": {
                    "Firewall": 25000,
                    "Monitoramento": 18000
                },
                "Redes": 22000
            },
            "Desenvolvimento": {
                "Frontend": 30000,
                "Backend": 45000,
                "DevOps": 28000,
                "QA": 15000
            },
            "Suporte": {
                "HelpDesk": 12000,
                "FieldSupport": 8000
            }
        },
        "RH": {
            "Recrutamento": 18000,
            "Treinamento": 22000,
            "Cultura": {
                "Eventos": 9000,
                "Brindes": 4000
            },
            "FolhaPagamento": 60000
        },
        "Financeiro": {
            "Contabilidade": 35000,
            "Planejamento": 20000,
            "Auditoria": 15000
        },
        "Jurídico": {
            "Contratos": 12000,
            "Compliance": 10000
        }
    },
    "Filial_Brasil": {
        "Comercial": {
            "Vendas": 85000,
            "PosVenda": 30000,
            "Parcerias": 20000
        },
        "Marketing": {
            "MidiasDigitais": 25000,
            "Eventos": 18000,
            "Branding": 22000
        },
        "Operacoes": {
            "Logistica": 40000,
            "Atendimento": 27000
        }
    },
    "Filial_Europa": {
        "TI": {
            "SuporteRegional": 30000,
            "Seguranca": 26000
        },
        "Comercial": {
            "Vendas": 70000,
            "RelacoesInternacionais": 35000
        }
    }
}

@auditor
def calcular_orcamento(estrutura, *departamentos_ignorados, **kwargs): # ← Função principal para o cálculo (recursiva)

    taxa_cambio = kwargs.get("taxa_cambio", 1)
    moeda_destino = kwargs.get("moeda_destino", "ORIGINAL")

    def dicionario_percorrer(num):
      total = 0

      for nome, valor in num.items():
          # Ignora o departamento inteiro (e seus subníveis)
          if nome in departamentos_ignorados:
            continue

          # Se for um subdepartamento, continua a recursão
          if isinstance(valor, dict):
            total += dicionario_percorrer(valor)

          # Se for um valor númerico, soma diretamente
          elif isinstance(valor, (int, float)):
            total += valor

      return total

    total_base = dicionario_percorrer(estrutura)
    orcamento_total = total_base * taxa_cambio

    print(f"Moeda de destino: {moeda_destino}")
    print(f"Taxa de câmbio: {taxa_cambio}")

    return orcamento_total

# Execução do script
if __name__ == "__main__":
    orcamento_total = calcular_orcamento(
        empresa_data,
        "RH", "Jurídico", # Departamentos que são ignorados
        taxa_cambio=5.20,
        moeda_destino="BRL"
    )

    print(f"ORÇAMENTO TOTAL FINAL: {orcamento_total:,.2f}")