# -*- coding: utf-8 -*-
"""Engenharia de Contexto e Lógica Física

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAIxmQrxTkq_atQ3Mfccz0DvqiuEdmfr
"""

def algoritmo_microclima_local():

 print("--- Algoritmo Microclima Local ---")



 #Dados retirados do weather channel (ou Weather.com)

 dados_locais_manha = [

   ["Praça", 24, 57, 143], # Nome, Temperatura, Umidade, IQAR

   ["MetroVM", 24, 56, 129],

   ["MetroCT", 24, 55, 119]

 ]



 dados_locais_noite = [

   ["Praça", 20, 81, 61],

   ["MetroVM", 20, 80, 62],

   ["MetroCT", 21, 80, 67]

 ]



 all_dados = dados_locais_manha + dados_locais_noite



 # Função auxiliar para categoria simplificada do match/case

 def iqar_para_match(valor_iqar):

   if valor_iqar <= 50:

     return "Boa"

   elif valor_iqar <= 100:

     return "Moderada"

   else:

     return "Ruim"



 # Função auxiliar para calculo da temperatura

 def conforto_temp(temp):

   if 20 <= temp <= 25:

     return 10.0

   elif 15 <= temp < 20 or 25 < temp <= 30:

     return 7.5

   elif 10 <= temp < 15 or 30 < temp <= 35:

     return 5.0

   else:

     return 2.5



 # Função auxiliar para calculo da umidade

 def conforto_umidade(umidade):

   if 50 <= umidade <= 70:

     return 10.0

   elif 40 <= umidade < 50 or 70 < umidade <= 80:

     return 7.5

   elif 30 <= umidade < 40 or 80 < umidade <= 90:

     return 5.0

   else:

     return 2.5



 # Função auxiliar para calculo do IQAr

 def conforto_iqar(valor_iqar):

   if valor_iqar <= 50:

     return 10.0

   elif valor_iqar <= 100:

     return 8.0

   elif valor_iqar <= 150:

     return 6.0

   elif valor_iqar <= 200:

     return 4.0

   elif valor_iqar <= 300:

     return 2.0

   else:

     return 0.0



 # Primeiro loop: Iterar sobre os locais

 for index, lista_dados_local in enumerate(all_dados):

  print(f"Analizando local {index + 1}...")

  nome_local = lista_dados_local[0]

  print(f"Nome do local: {nome_local}")



  if len(lista_dados_local) >= 4:

    temp = lista_dados_local[1]

    umidade = lista_dados_local[2]

    valor_iqar = lista_dados_local[3]



    print(f"Temperatura: {temp}°C, Umidade: {umidade}%, IQAR: {valor_iqar}")



    # Segundo loop: Iterar sobre as métricas do local e aplicar a análise

    metricas_para_analisar = [

      (temp, "temperatura"),

      (umidade, "umidade"),

      (valor_iqar, "iqar")

    ]



    for valor_metrica, tipo_metrica in metricas_para_analisar:

      if tipo_metrica == "temperatura":

        # Análise de Temperatura

        if valor_metrica >= 30:

          print(f"→ Temperatura: {valor_metrica}°C (Muito quente)")

        elif valor_metrica >= 20:

          print(f"→ Temperatura: {valor_metrica}°C (Quente)")

        else:

          print(f"→ Temperatura: {valor_metrica}°C (Frio)")

      elif tipo_metrica == "umidade":

        # Análise de Umidade

        if valor_metrica >= 80:

          print(f"→ Umidade: {valor_metrica}% (Muito chuvoso)")

        elif valor_metrica >= 60:

          print(f"→ Umidade: {valor_metrica}% (Chuvoso)")

        elif valor_metrica >= 50:

          print(f"→ Umidade: {valor_metrica}% (Nublado)")

        else:

          print(f"→ Umidade: {valor_metrica}% (Sol)")

      elif tipo_metrica == "iqar":

        # Análise de IQAr usando match/case

        categoria_geral_iqar = iqar_para_match(valor_metrica)

        match categoria_geral_iqar:

          case "Boa":

            print("→ Qualidade do Ar: Boa (Ar bom para todos)")

          case "Moderada":

            print("→ Qualidade do Ar: Moderada (Ar aceitável, mas pode ser insalubre para grupos sensíveis)")

          case "Ruim":

            print("→ Qualidade do Ar: Ruim")

            # Feedback mais detalhado dentro de 'Ruim'

            if valor_metrica >= 300:

              print(" (Detalhe: Ar Criticamente Insalubre!!!)")

            elif valor_metrica >= 201:

              print(" (Detalhe: Ar Muito Insalubre (Alerta de Saúde!))")

            elif valor_metrica >= 121:

              print(" (Detalhe: Ar Insalubre para todos)")

            elif valor_metrica >= 81:

              print(" (Detalhe: Ar Insalubre para grupos sensíveis)")

            else: # Fallback para completude, embora deva ser coberto

              print(" (Detalhe: Ar com problemas de qualidade)")

          case _: # Não deve ser alcançado com a função auxiliar

            print("→ Qualidade do Ar: Categoria desconhecida.")



    # Calculos

    score_temp = conforto_temp(temp)

    score_umidade = conforto_umidade(umidade)

    score_iqar = conforto_iqar(valor_iqar)



    # Média simples pra pontuação conforto

    score_conforto_urbano = (score_temp + score_umidade + score_iqar) / 3

    print(f"→ Nota de Conforto Urbano: {score_conforto_urbano:.2f}/10")



  else:

    print("Dados incompletos para análise detalhada neste local.")



algoritmo_microclima_local()